Plater.lua
Don't show the selection frame on the personal bar when changing the enemy or friendly box selection spaces.
=> Don't show the selection frame on the personal bar

Plater.lua, Plater_DefaultSettings.lua, Plater_OptionsPanel.lua
Adding options to chose and enable/disable the friend, guild and class color for the name/guild texts.
Moving the text color options to a separate block, away from the other name text options, to not disturb the menu.
This still might need some cleanup, but it is working and ready for a review. :)
=> - Additional options for friendly players name colors

Plater.lua
Somehow Blizzard resets the nameplate size after the interface options are closed. Hooking into OnHide of InterfaceOptionsFrame to call UpdatePlateClickSpace.
=> -fix nameplate size after interface-options menu closes

Plater.lua, Plater_OptionsPanel.lua
With this change, the "Only Show Player Name" option will no longer fully overwrite the "Only Damaged Players" option for friendly nameplates.
In case both are selected either name or bar will be shown, depending on the health of the player.
Current behavior:
New bevavior:
=> - change behavior of friendly players "only name" or "only damaged" options

Plater.lua, Plater_DefaultSettings.lua, Plater_OptionsPanel.lua
Adding the auraType to the auraIconFrame to start supporting rage effect tracking. Can be used to track any other aura type as well:
Disease", "Poison", "Curse", "Magic", "" (yes, empty string. this is how Blizzard rolls apparently) for enrage and nil/"none" for uncategorized.
=> - Adding enrage to normal / special buff tracking and '.auraType' to the auraIconFrame

Plater.lua
If the quest mob has the same name as the quest, the QuestAmountCurrent and QuestAmountTotal were not recognized properly.
Adding recognition for % based quests.
=> -fixing named quest mob and % based quest recognition

Plater.lua
If an other tank is tanking the unit and the unit is targeting a non-tank unit, this was not recognized. We need to check threat status of all other tanks instead of the current target if you are tank and not tanking the unit.
=> Fixing off tank aggro recognition

Plater.lua
The quest amount for % based quests was only showing one digit always. Now shows two digits for >9%.
=> fixing % quest amount recognition

Plater.lua
When both "only the name" and "only damaged" for friendly players are selected, the nameplate did not update properly when the target was healed to full health or damaged.
This fix forces a proper update when switching between both states.
=> - fixing friendly player name/healthbar switch for only damaged + only name options

Plater.lua
Part 2: When both "only the name" and "only damaged" for friendly players are selected, the nameplate did not update properly when the target was healed to full health or damaged.
This fix forces a proper update when switching between both states.
=> - fixing friendly player name/healthbar switch for only damaged + only name options (part 2)

Plater_OptionsPanel.lua
"Copy from" is broken because of the tab re-order. This corrects the tab indexes.
=> - fixing the "copy from" actions

Plater.lua
Improved quest amount lookup by using look-ahead regex to make it more consistent.
For better handling: Setting default values to nil if no amount is displayed.
=> - improve quest amount recognition

Plater.lua, Plater_DefaultSettings.lua, Plater_OptionsPanel.lua
- adding usage of DebuffTypeColor for aura border colors
Default aura border will now be matched against DebuffTypeColor, a Blizzard global.
Options added to use this feature for Extra Icons as well.
- adding option to use blizzard type colors for buff borders
=> Debuff type color update

Plater.lua
This prevents incorrect quest flagging if one of multiple quests for this mob is finished.
=> - scan all quests instead of finishing after first match

Plater.lua, Plater_OptionsPanel.lua
Reworked the buff special filtering to accept either names or spellIDs.
This helps in better filtering for specific special buffs/debuffs, as duplicates with the same name can now excluded using a specific spellID.
=> - Buff Special now distinguishing betwenn spellIDs and spell names

Plater.lua, libs/LibCustomGlow-1.0/CHANGES.txt, libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua, libs/LibCustomGlow-1.0/LibCustomGlow-1.0.toc, libs/LibCustomGlow-1.0/LibCustomGlow-1.0.xml, libs/LibCustomGlow-1.0/LibStub/LibStub.lua, libs/LibCustomGlow-1.0/LibStub/LibStub.toc, libs/LibCustomGlow-1.0/LibStub/tests/test.lua, libs/LibCustomGlow-1.0/LibStub/tests/test2.lua, libs/LibCustomGlow-1.0/LibStub/tests/test3.lua, libs/LibCustomGlow-1.0/LibStub/tests/test4.lua, libs/libs.xml
Adding LibCustomGlow-1.0 and Plater functions to create glow effects on frames based on the lib.
Test-Mod for target glows: https://wago.io/ax6AS_lYG
Adds the following functions:
- Plater.StartGlow(frame, color, options, key) -- start glow effect according to options, defaults to "button"
- Plater.StartAntsGlow(frame, color, options, key) -- start "ants" glow
- Plater.StartPixelGlow(frame, color, options, key) -- start "pixel" glow
- Plater.StartButtonGlow(frame, color, options, key) -- start "button" glow
- Plater.StopGlow(unitFrame.healthBar, glowType, key) -- stop all glow effects or a specific one
- Plater.StopAntsGlow(frame, key) -- stop an ants glow
- Plater.StopPixelGlow(frame, key) -- stop a pixel glow
- Plater.StopButtonGlow(frame, key) -- stop a button glow
Options …
=> Adding LibCustomGlow support

Plater.lua
This enables addons like MoveAnything to correctly gather information about the protected status of the frame. This might need to be added for child-frames as well.
=> - adding IsProtected function to Plater namepaltes

Plater.lua, Plater_DefaultSettings.lua, Plater_OptionsPanel.lua
Adding a "solo" color for DPS which can be toggled on to overwrite all other threat state colors when not grouped. This adresses feature request #34.
=> - add "solo" options for threat colors

Plater_OptionsPanel.lua
When importing a profile there is now a check in place to ensure the user is aware that he/she is overwriting an existing profile and given the chance to change the profile name.
In addition all profiles (existing and new) are reset to default values prior to the import. This should fix the broken mods issue (unecessary events with code from other mods) which occurred during import for several users and will ensure newly added default values, which are not present in the imported profile, are populated correctly.
=> - "Import Profile" is now asking to overwrite an existing profile

Plater.lua
If a spell for an animation is not found, it would throw a nil-error. This can happen with old profiles if the spell has been removed from the game.
=> - fixing bug with spell-animation settings

libs/DF/fw.lua, libs/DF/panel.lua
The UNIT_SPELLCAST_DELAYED event could hide the castbar if the pased cast time was lower than the push back amount.
=> - fixing spell cast delayed event hiding the castbar in some cases

Plater_OptionsPanel.lua
The options have been added to the settings menu. The base was already existing but could not be modified properly.
Satisfies #48
=> - adding text options for the npc title

Plater.lua, Plater_DefaultSettings.lua
I inserted a few alpha values of 1 where hardcoded values were set. Other than that, I *think* this should just work. Existing calls that omit the alpha argument shouldn't break.
=> Add alpha to SetNameplateColor

libs/DF/spells.lua
This PR adds the different Shaman hex IDs to the list of Crowd Control spells.
These hexes were pulled from the See Also section at: https://www.wowhead.com/spell=51514/hex#see-also-ability
=> Add glyphed Shaman hexes.

Plater_Auras.lua
Noticed that the custom borders for 'Buff Special' weren't working.
This change updates `Plater.AddExtraIcon` to use the logic found in `Plater.AddAura` when determining offensive / defensive border colors.
Side note, I noticed `Plater.AddAura` uses `DF.CrowdControlSpells[spellId]` for checking if the aura is CC while `Plater.AddExtraIcon` uses `CROWDCONTROL_AURA_NAMES[spellName]`. I couldn't find any other uses of `CROWDCONTROL_AURA_NAMES` - would it make sense to remove `CROWDCONTROL_AURA_NAMES` all together and switch to `DF.CrowdControlSpells`?
Love the addon - thanks for all the work put into it.
=> fix extra icon border not showing for offensive / defensive auras

Plater.lua
Add function to allow nameplate access to the collected bg information. This will allow a more accurate healer indicator since we can use the same data used for the spec icon.
=> Add function to allow nameplate access to the collected bg information

Plater.lua
I've been seeing an error from bug grabber for Plater for the past couple of days only when playing on my brewmaster monk and have traced it down to this part of the code.
It appears that the `resourceFrame` logic is inverted and only tries to call the `resourceFrame` only if the value isn't set which will cause. I believe this only happens on my brewmaster monk as stagger is treated as an `alternatePowerFrame` and it will go down this code path.
This is the full bug grabber output:
```
500x Plater/Plater.lua:5168: attempt to index local 'resourceFrame' (a nil value)
[string "@Plater/Plater.lua"]:5168: in function `UpdateResourceFrame'
[string "@Plater/Plater.lua"]:4991: in function <Plater/Plater.lua:4987>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetupClassNameplateBars' …
```
=> Bugfix: Call resourceFrame whenever the value is set

Plater_Auras.lua
This bug is noticeable on the 10.2 PTR for rogues, as the Underhanded Upper Hand talent seems to work by applying a time mod of 100 to the buffs it pauses when it "pauses" them, so the ModRate changes with buff state.
=> Account for ModRate on Aura Update

Plater_ChangeLog.lua, Plater_ScriptingPanels.lua
Wanted to customize the layout of the interrupt message and found these members in the code, just not in the scripting panels
=> Added missing interrupt members to castBar scripting panel

Plater_CastColorPanels.lua
Add Plater.SetCastBarColorsForScript to set both interruptible and uninterruptible cast bar colors. Useful for scripts that want to recolor the uninterruptible casts, instead of always having it be the default (grey).
=> Add Plater.SetCastBarColorsForScript 

Plater_CastColorPanels.lua
Missed this when renaming the variables.
=> Fix typo in SetCastBarColorsForScript

Plater.lua
At the momnet funtion CheckAuras is unusable due to undefined variable unitFrame in local scope
=> fix CheckAuras function, unitFrame variable is not in scope

Plater_ScriptingPanels.lua
Confirmed that this is indeed the order of execution, but based on the original tooltip it was rather unclear to me how it behaved.
=> Updated the wording of the priority tooltip
